/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes.$clienteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes': typeof ClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/': typeof ClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clientes/$clienteId' | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clientes/$clienteId' | '/clientes'
  id: '__root__' | '/' | '/clientes/$clienteId' | '/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesClienteIdRoute: ClientesClienteIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
